// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4y2G9ek0w2Aq9rZ1LP-JJ0eSrQBI2D8I',
    appId: '1:696606471394:web:fcb4741df497776d595abb',
    messagingSenderId: '696606471394',
    projectId: 'my-app-wtc',
    authDomain: 'my-app-wtc.firebaseapp.com',
    storageBucket: 'my-app-wtc.appspot.com',
    measurementId: 'G-9HGE1GD8VK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPUiFBmi_rkPS88XJj67lYmVHN0EyTTZc',
    appId: '1:696606471394:android:b5657c6ce5955666595abb',
    messagingSenderId: '696606471394',
    projectId: 'my-app-wtc',
    storageBucket: 'my-app-wtc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhf6AurVis-tQFnC4lyOidzp02L9wymAk',
    appId: '1:696606471394:ios:fb948e7ac5cb2723595abb',
    messagingSenderId: '696606471394',
    projectId: 'my-app-wtc',
    storageBucket: 'my-app-wtc.appspot.com',
    iosClientId: '696606471394-t9e224e821kmpg5s7obq97hd6jnqli9d.apps.googleusercontent.com',
    iosBundleId: 'za.co.wethinkcode.widgetsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhf6AurVis-tQFnC4lyOidzp02L9wymAk',
    appId: '1:696606471394:ios:fb948e7ac5cb2723595abb',
    messagingSenderId: '696606471394',
    projectId: 'my-app-wtc',
    storageBucket: 'my-app-wtc.appspot.com',
    iosClientId: '696606471394-t9e224e821kmpg5s7obq97hd6jnqli9d.apps.googleusercontent.com',
    iosBundleId: 'za.co.wethinkcode.widgetsApp',
  );
}
